//Our buttons
var buttonColours = ["red", "blue", "green", "yellow"];
//Contains the game pattern generated by the game
var gamePattern = [];
//Contains the pattern clicked by the user
var userClickedPattern = [];

//variable started is for the start of the pattern
var started = false;

//At the start of the game the level is zero
var level = 0;

//Is for the start of the game which is detected by a keypress, as soon as the key is pressed,
//the started becomes true(mneaning the game has started), and nextseequence is called
$(document).keypress(function() {
  if (!started) {
    $("#level-title").text("Level " + level);
    nextSequence();
    started = true;
  }
});
//On clicking a button this function becomes active
$(".btn").click(function() {
  //The user chosen colour is selected and it is added to the array userClickedPattern
  var userChosenColour = $(this).attr("id");
  userClickedPattern.push(userChosenColour);
  //sound and Animation are done for user chosen randomChosenColour
  playSound(userChosenColour);
  animatePress(userChosenColour);

  //Check answer function is called after the user has clicked with the index of the last pressed button in it
  checkAnswer(userClickedPattern.length-1);
});
function startOver(){
  level=0;
  started=false;
  gamePattern.length=0;
}

//Function checkAnswer is called after every user click to look that upto this point the sequence has been correct or not
function checkAnswer(currentLevel) {

    //If the button at current level for gamePattern and userClickedPattern is same , success is logged
    if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {

      console.log("success");

      //After every successfull checking, it is checked that all the buttons are pressed or not, if yes then we go on for the next sequence after 1000
      //ms,i.e.
      //one more button from machine side
      if (userClickedPattern.length === gamePattern.length){


        setTimeout(function () {
          nextSequence();
        }, 1000);

      }

    }
    //If the button pressed is not same then else is activated
    else {
        var audio = new Audio("sounds/wrong.mp3");
        audio.play();
        $("body").addClass("game-over");
        setTimeout(function(){
          $("body").removeClass("game-over");
        },100);
        $("#level-title").text("Game Over, Press Any Key to Restart");
        startOver();

    }

}
//Goes for new input from machine side
function nextSequence() {

//userClickedPattern is empty at the start
  userClickedPattern = [];
//level is increased everytime the function is called
  level++;
  $("#level-title").text("Level " + level);

  var randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);
  //The button chosen by the machine is animated --
  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  playSound(randomChosenColour);
}
//playsound according to the id of the button
function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}
//Animation according to the id of our colour
function animatePress(currentColor) {
  $("#" + currentColor).addClass("pressed");
  setTimeout(function () {
    $("#" + currentColor).removeClass("pressed");
  }, 100);
}
